# https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["../../node_modules"]
optimizer = true
optimizer_runs = 10_000
solc = "0.8.30"
evm_version = "prague"
ignored_warnings_from = ["../../node_modules"]

[rpc_endpoints]
rpc_url = "${RPC_URL}"

[profile.ci]
verbosity = 4

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
