[package]
name = "gas_bench_scale1"
type = "bin"
authors = ["gas-benchmark"]
compiler_version = ">=1.0.0"

[dependencies]
zkemail = { path = "../../../../../../zkemail.nr/lib" }
sha256 = { git = "https://github.com/noir-lang/sha256", tag = "v0.1.2" }
